name: 'FBAlves-PHP-CS-Fixer'
author: 'Fernando Braga Alves'
description: 'Checks code style'
inputs:
  command:
    description: 'Command to be executed (e.g., check or fix)'
    required: true
    default: 'check'
  flags:
    description: 'Flags to customize the command (e.g., --path-mode=intersection, --diff, --rules=@PSR12)'
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/php-cs-fixer/php-cs-fixer:3.75-php8.3'
  args:
    - ${{ inputs.command }}

branding:
  icon: 'check'
  color: 'green'